version: '3.8'

services:
  app:
    image: kth7186/pytorch:1.10.0-cuda11.3-cudnn8-runtime-zsh-setup
    container_name: DockerTorch_2
    ipc: host
    ports:
      - 5686:8888
    volumes:
      - ../:/app/
      - ~/Data/SCCNN:/app/Data/
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: [ "/bin/zsh", "-c" ]
    command:
      - |
        /bin/zsh
