
# your image
FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime

# WORKDIR /app

# RUN apt-get install git -y

# COPY requirements.txt requirements.txt
# RUN python -m pip install -r requirements.txt --upgrade
