network.hidden_size:
  _type: choice
  _value: [128, 256, 512, 1024]

network.dropout_p:
  _type: uniform
  _value: [0, 0.5]

optimizer.optimizer:
  _type: choice
  _value: [SGD, Adam]

optimizer.lr:
  _type: choice
  _value: [0.0001, 0.001, 0.01, 0.1]

log.precision:
  _type: choice
  _value: [16, 32] 

loader.train.batch_size:
  _type: choice
  _value: [16, 20, 32, 64, 128]